# Selecciona la imagen base
FROM node:lts-alpine

# Establece un directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json (si está disponible)
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Expone el puerto que usará tu aplicación
EXPOSE 5173

# Comando para ejecutar tu aplicación
CMD ["npm", "run", "dev"]

